version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/taskmanager
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=your_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update  
    depends_on:
      db:
        condition: service_healthy  
    restart: always 

  db:
    image: postgres:15.3
    environment:
      - POSTGRES_DB=taskmanager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U postgres -d taskmanager"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  adminer:
    image: adminer:4.8.1
    ports:
      - "8081:8080"
    depends_on:
      - db
    restart: always 

volumes:
  postgres_data:
